export type DemoRole =
  | "super_admin"
  | "hr_manager"
  | "department_manager"
  | "hr_specialist"
  | "employee";

export interface DemoEmployee {
  id: string;
  employeeNumber: string;
  fullName: string;
  fullNameAr: string;
  email: string;
  phone: string;
  photoUrl: string;
  role: DemoRole;
  jobTitle: string;
  jobTitleAr: string;
  department: string;
  departmentId: string;
  branchId: string;
  managerId: string | null;
  nationality: "saudi" | "expat";
  gosiCohort: "legacy" | "new_entrant" | "occupational_hazards_only";
  hireDate: string;
  status: "active" | "on_leave" | "notice_period";
  workPattern: string;
  salary: { basic: number; housing: number; transport: number };
  bankName: string;
  maskedIban: string;
  healthPlanId: string;
  maskedIdentity: string;
  skills: string[];
}

const employees: DemoEmployee[] = [
  {
    id: "emp-reem",
    employeeNumber: "RES-1001",
    fullName: "Reem Al-Harbi",
    fullNameAr: "ريم الحربي",
    email: "reem.alharbi@rukn-energy.example",
    phone: "+966 5X XXX 1101",
    photoUrl: "/demo/people/reem-alharbi.svg",
    role: "hr_manager",
    jobTitle: "People & Culture Director",
    jobTitleAr: "مديرة الموارد البشرية والثقافة",
    department: "People & Culture",
    departmentId: "dept-people",
    branchId: "riyadh-hq",
    managerId: null,
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2021-03-14",
    status: "active",
    workPattern: "Riyadh corporate · Sun–Thu",
    salary: { basic: 32_000, housing: 8_000, transport: 2_500 },
    bankName: "Saudi National Bank",
    maskedIban: "SA•• •••• •••• 7519",
    healthPlanId: "benefit-medical-executive",
    maskedIdentity: "National ID •••• 4821",
    skills: ["Saudi labor law", "Workforce planning", "Executive coaching"],
  },
  {
    id: "emp-fahad",
    employeeNumber: "RES-1002",
    fullName: "Fahad Al-Qahtani",
    fullNameAr: "فهد القحطاني",
    email: "fahad.alqahtani@rukn-energy.example",
    phone: "+966 5X XXX 1102",
    photoUrl: "/demo/people/fahad-alqahtani.svg",
    role: "department_manager",
    jobTitle: "Eastern Operations Manager",
    jobTitleAr: "مدير العمليات بالمنطقة الشرقية",
    department: "Field Operations",
    departmentId: "dept-field",
    branchId: "dhahran-ops",
    managerId: "emp-reem",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2020-09-01",
    status: "active",
    workPattern: "Dhahran operations · rotating coverage",
    salary: { basic: 28_500, housing: 7_125, transport: 2_200 },
    bankName: "Al Rajhi Bank",
    maskedIban: "SA•• •••• •••• 2204",
    healthPlanId: "benefit-medical-family",
    maskedIdentity: "National ID •••• 7350",
    skills: ["Well services", "Operational leadership", "HSE governance"],
  },
  {
    id: "emp-aisha",
    employeeNumber: "RES-1003",
    fullName: "Aisha Al-Otaibi",
    fullNameAr: "عائشة العتيبي",
    email: "aisha.alotaibi@rukn-energy.example",
    phone: "+966 5X XXX 1103",
    photoUrl: "/demo/people/aisha-alotaibi.svg",
    role: "hr_specialist",
    jobTitle: "Payroll & GOSI Specialist",
    jobTitleAr: "أخصائية الرواتب والتأمينات",
    department: "People & Culture",
    departmentId: "dept-people",
    branchId: "riyadh-hq",
    managerId: "emp-reem",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2022-01-09",
    status: "active",
    workPattern: "Riyadh corporate · hybrid",
    salary: { basic: 17_800, housing: 4_450, transport: 1_500 },
    bankName: "Riyad Bank",
    maskedIban: "SA•• •••• •••• 2604",
    healthPlanId: "benefit-medical-family",
    maskedIdentity: "National ID •••• 2604",
    skills: ["Payroll controls", "GOSI", "Mudad wage protection"],
  },
  {
    id: "emp-omar",
    employeeNumber: "RES-1004",
    fullName: "Omar Nasser Al-Dossary",
    fullNameAr: "عمر ناصر الدوسري",
    email: "omar.aldossary@rukn-energy.example",
    phone: "+966 5X XXX 1104",
    photoUrl: "/demo/people/omar-aldossary.svg",
    role: "employee",
    jobTitle: "Field Engineer",
    jobTitleAr: "مهندس ميداني",
    department: "Field Operations",
    departmentId: "dept-field",
    branchId: "dhahran-ops",
    managerId: "emp-fahad",
    nationality: "saudi",
    gosiCohort: "new_entrant",
    hireDate: "2026-05-03",
    status: "active",
    workPattern: "Dhahran field · 14/7 rotation",
    salary: { basic: 14_500, housing: 3_625, transport: 1_350 },
    bankName: "Saudi National Bank",
    maskedIban: "SA•• •••• •••• 9182",
    healthPlanId: "benefit-medical-standard",
    maskedIdentity: "National ID •••• 9182",
    skills: ["Production logging", "Permit to work", "Arabic/English reporting"],
  },
  {
    id: "emp-priya",
    employeeNumber: "RES-1005",
    fullName: "Priya Menon",
    fullNameAr: "بريا مينون",
    email: "priya.menon@rukn-energy.example",
    phone: "+966 5X XXX 1105",
    photoUrl: "/demo/people/priya-menon.svg",
    role: "employee",
    jobTitle: "HSE Data Analyst",
    jobTitleAr: "محللة بيانات الصحة والسلامة",
    department: "HSE & Quality",
    departmentId: "dept-hse",
    branchId: "dhahran-ops",
    managerId: "emp-salman",
    nationality: "expat",
    gosiCohort: "occupational_hazards_only",
    hireDate: "2023-08-20",
    status: "notice_period",
    workPattern: "Dhahran operations · Sun–Thu",
    salary: { basic: 12_800, housing: 3_200, transport: 1_200 },
    bankName: "Alinma Bank",
    maskedIban: "SA•• •••• •••• 6137",
    healthPlanId: "benefit-medical-standard",
    maskedIdentity: "Iqama •••• 6137",
    skills: ["Power BI", "Incident analytics", "ISO 45001"],
  },
  {
    id: "emp-noura",
    employeeNumber: "RES-1006",
    fullName: "Noura Al-Shehri",
    fullNameAr: "نورة الشهري",
    email: "noura.alshehri@rukn-energy.example",
    phone: "+966 5X XXX 1106",
    photoUrl: "/demo/people/noura-alshehri.svg",
    role: "employee",
    jobTitle: "Talent Acquisition Lead",
    jobTitleAr: "قائدة استقطاب المواهب",
    department: "People & Culture",
    departmentId: "dept-people",
    branchId: "riyadh-hq",
    managerId: "emp-reem",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2023-02-12",
    status: "active",
    workPattern: "Riyadh corporate · hybrid",
    salary: { basic: 16_600, housing: 4_150, transport: 1_400 },
    bankName: "Bank Albilad",
    maskedIban: "SA•• •••• •••• 4106",
    healthPlanId: "benefit-medical-family",
    maskedIdentity: "National ID •••• 4106",
    skills: ["Technical recruitment", "Qiwa offers", "Employer branding"],
  },
  {
    id: "emp-khalid",
    employeeNumber: "RES-1007",
    fullName: "Khalid Al-Zahrani",
    fullNameAr: "خالد الزهراني",
    email: "khalid.alzahrani@rukn-energy.example",
    phone: "+966 5X XXX 1107",
    photoUrl: "/demo/people/khalid-alzahrani.svg",
    role: "department_manager",
    jobTitle: "Projects & PMO Director",
    jobTitleAr: "مدير المشاريع ومكتب إدارة المشاريع",
    department: "Projects & PMO",
    departmentId: "dept-projects",
    branchId: "jubail-site",
    managerId: "emp-reem",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2019-11-03",
    status: "active",
    workPattern: "Jubail project site · Sun–Thu",
    salary: { basic: 30_000, housing: 7_500, transport: 2_400 },
    bankName: "Saudi Awwal Bank",
    maskedIban: "SA•• •••• •••• 6107",
    healthPlanId: "benefit-medical-executive",
    maskedIdentity: "National ID •••• 6107",
    skills: ["Portfolio governance", "EPC delivery", "Contract management"],
  },
  {
    id: "emp-mariam",
    employeeNumber: "RES-1008",
    fullName: "Mariam Al-Anazi",
    fullNameAr: "مريم العنزي",
    email: "mariam.alanazi@rukn-energy.example",
    phone: "+966 5X XXX 1108",
    photoUrl: "/demo/people/mariam-alanazi.svg",
    role: "department_manager",
    jobTitle: "Finance & Procurement Manager",
    jobTitleAr: "مديرة المالية والمشتريات",
    department: "Finance & Procurement",
    departmentId: "dept-finance",
    branchId: "riyadh-hq",
    managerId: "emp-reem",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2020-06-14",
    status: "active",
    workPattern: "Riyadh corporate · Sun–Thu",
    salary: { basic: 26_000, housing: 6_500, transport: 2_100 },
    bankName: "Saudi National Bank",
    maskedIban: "SA•• •••• •••• 7108",
    healthPlanId: "benefit-medical-family",
    maskedIdentity: "National ID •••• 7108",
    skills: ["Budget controls", "Procurement", "Payroll reconciliation"],
  },
  {
    id: "emp-yousef",
    employeeNumber: "RES-1009",
    fullName: "Yousef Al-Amri",
    fullNameAr: "يوسف العمري",
    email: "yousef.alamri@rukn-energy.example",
    phone: "+966 5X XXX 1109",
    photoUrl: "/demo/people/yousef-alamri.svg",
    role: "employee",
    jobTitle: "Senior Drilling Engineer",
    jobTitleAr: "مهندس حفر أول",
    department: "Field Operations",
    departmentId: "dept-field",
    branchId: "dhahran-ops",
    managerId: "emp-fahad",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2018-04-22",
    status: "active",
    workPattern: "Dhahran field · 14/7 rotation",
    salary: { basic: 22_000, housing: 5_500, transport: 1_800 },
    bankName: "Al Rajhi Bank",
    maskedIban: "SA•• •••• •••• 8109",
    healthPlanId: "benefit-medical-family",
    maskedIdentity: "National ID •••• 8109",
    skills: ["Drilling programs", "Well control", "Contractor supervision"],
  },
  {
    id: "emp-ahmed",
    employeeNumber: "RES-1010",
    fullName: "Ahmed Khan",
    fullNameAr: "أحمد خان",
    email: "ahmed.khan@rukn-energy.example",
    phone: "+966 5X XXX 1110",
    photoUrl: "/demo/people/ahmed-khan.svg",
    role: "employee",
    jobTitle: "Maintenance Supervisor",
    jobTitleAr: "مشرف الصيانة",
    department: "Field Operations",
    departmentId: "dept-field",
    branchId: "dhahran-ops",
    managerId: "emp-fahad",
    nationality: "expat",
    gosiCohort: "occupational_hazards_only",
    hireDate: "2022-10-16",
    status: "active",
    workPattern: "Dhahran maintenance · rotating shift",
    salary: { basic: 15_000, housing: 3_750, transport: 1_400 },
    bankName: "Arab National Bank",
    maskedIban: "SA•• •••• •••• 9110",
    healthPlanId: "benefit-medical-standard",
    maskedIdentity: "Iqama •••• 9110",
    skills: ["Preventive maintenance", "CMMS", "Equipment reliability"],
  },
  {
    id: "emp-lina",
    employeeNumber: "RES-1011",
    fullName: "Lina Al-Haddad",
    fullNameAr: "لينا الحداد",
    email: "lina.alhaddad@rukn-energy.example",
    phone: "+966 5X XXX 1111",
    photoUrl: "/demo/people/lina-alhaddad.svg",
    role: "employee",
    jobTitle: "Project Coordinator",
    jobTitleAr: "منسقة مشاريع",
    department: "Projects & PMO",
    departmentId: "dept-projects",
    branchId: "jubail-site",
    managerId: "emp-khalid",
    nationality: "saudi",
    gosiCohort: "new_entrant",
    hireDate: "2025-11-02",
    status: "active",
    workPattern: "Jubail project site · Sun–Thu",
    salary: { basic: 13_500, housing: 3_375, transport: 1_300 },
    bankName: "Banque Saudi Fransi",
    maskedIban: "SA•• •••• •••• 1111",
    healthPlanId: "benefit-medical-standard",
    maskedIdentity: "National ID •••• 1111",
    skills: ["Project controls", "Document control", "Stakeholder reporting"],
  },
  {
    id: "emp-salman",
    employeeNumber: "RES-1012",
    fullName: "Salman Al-Rashidi",
    fullNameAr: "سلمان الرشيدي",
    email: "salman.alrashidi@rukn-energy.example",
    phone: "+966 5X XXX 1112",
    photoUrl: "/demo/people/salman-alrashidi.svg",
    role: "department_manager",
    jobTitle: "HSE & Quality Manager",
    jobTitleAr: "مدير الصحة والسلامة والجودة",
    department: "HSE & Quality",
    departmentId: "dept-hse",
    branchId: "dhahran-ops",
    managerId: "emp-fahad",
    nationality: "saudi",
    gosiCohort: "legacy",
    hireDate: "2021-07-18",
    status: "active",
    workPattern: "Dhahran operations · Sun–Thu",
    salary: { basic: 19_500, housing: 4_875, transport: 1_650 },
    bankName: "Alinma Bank",
    maskedIban: "SA•• •••• •••• 2112",
    healthPlanId: "benefit-medical-family",
    maskedIdentity: "National ID •••• 2112",
    skills: ["ISO 45001", "Incident command", "Quality audits"],
  },
];

const departments = [
  { id: "dept-people", name: "People & Culture", nameAr: "الموارد البشرية والثقافة", code: "PC-100", headEmployeeId: "emp-reem", employeeCount: 3, budget: 2_400_000 },
  { id: "dept-field", name: "Field Operations", nameAr: "العمليات الميدانية", code: "FO-200", headEmployeeId: "emp-fahad", employeeCount: 4, budget: 8_750_000 },
  { id: "dept-projects", name: "Projects & PMO", nameAr: "المشاريع ومكتب إدارة المشاريع", code: "PMO-300", headEmployeeId: "emp-khalid", employeeCount: 2, budget: 6_200_000 },
  { id: "dept-finance", name: "Finance & Procurement", nameAr: "المالية والمشتريات", code: "FN-400", headEmployeeId: "emp-mariam", employeeCount: 1, budget: 1_900_000 },
  { id: "dept-hse", name: "HSE & Quality", nameAr: "الصحة والسلامة والجودة", code: "HQ-500", headEmployeeId: "emp-salman", employeeCount: 2, budget: 2_850_000 },
] as const;

const branches = [
  { id: "riyadh-hq", name: "Riyadh Corporate Office", nameAr: "المكتب الرئيسي بالرياض", city: "Riyadh", type: "Head office", employeeCount: 4 },
  { id: "dhahran-ops", name: "Dhahran Operations Base", nameAr: "قاعدة عمليات الظهران", city: "Dhahran", type: "Operations branch", employeeCount: 6 },
  { id: "jubail-site", name: "Jubail Project Office", nameAr: "مكتب مشروع الجبيل", city: "Jubail", type: "Project site", employeeCount: 2 },
] as const;

const projects = [
  {
    id: "project-jafurah",
    code: "PRJ-2601",
    name: "Jafurah Well Services Ramp-up",
    client: "Fictional National Energy Client",
    departmentId: "dept-projects",
    branchId: "dhahran-ops",
    managerId: "emp-khalid",
    status: "active",
    progress: 68,
    startDate: "2026-02-01",
    endDate: "2026-11-30",
    budget: 4_800_000,
    teamEmployeeIds: ["emp-khalid", "emp-fahad", "emp-yousef", "emp-omar", "emp-salman", "emp-lina"],
  },
  {
    id: "project-hse-digital",
    code: "PRJ-2602",
    name: "Dhahran HSE Digitization",
    client: "Rukn Energy internal",
    departmentId: "dept-hse",
    branchId: "dhahran-ops",
    managerId: "emp-salman",
    status: "active",
    progress: 82,
    startDate: "2026-01-15",
    endDate: "2026-09-30",
    budget: 950_000,
    teamEmployeeIds: ["emp-salman", "emp-priya", "emp-aisha", "emp-lina"],
  },
  {
    id: "project-hr-transform",
    code: "PRJ-2603",
    name: "Riyadh HR & Payroll Transformation",
    client: "Rukn Energy internal",
    departmentId: "dept-people",
    branchId: "riyadh-hq",
    managerId: "emp-reem",
    status: "active",
    progress: 74,
    startDate: "2026-03-01",
    endDate: "2026-10-31",
    budget: 1_250_000,
    teamEmployeeIds: ["emp-reem", "emp-aisha", "emp-noura", "emp-mariam"],
  },
  {
    id: "project-jubail-shutdown",
    code: "PRJ-2604",
    name: "Jubail Shutdown Readiness",
    client: "Fictional Petrochemical Client",
    departmentId: "dept-field",
    branchId: "jubail-site",
    managerId: "emp-fahad",
    status: "planning",
    progress: 35,
    startDate: "2026-06-15",
    endDate: "2026-12-15",
    budget: 2_100_000,
    teamEmployeeIds: ["emp-fahad", "emp-ahmed", "emp-yousef", "emp-salman", "emp-lina"],
  },
] as const;

const assignmentAllocation: Record<string, number> = {
  "project-jafurah:emp-khalid": 35,
  "project-jafurah:emp-fahad": 25,
  "project-jafurah:emp-yousef": 70,
  "project-jafurah:emp-omar": 80,
  "project-jafurah:emp-salman": 20,
  "project-jafurah:emp-lina": 35,
  "project-hse-digital:emp-salman": 35,
  "project-hse-digital:emp-priya": 70,
  "project-hse-digital:emp-aisha": 10,
  "project-hse-digital:emp-lina": 20,
  "project-hr-transform:emp-reem": 20,
  "project-hr-transform:emp-aisha": 35,
  "project-hr-transform:emp-noura": 45,
  "project-hr-transform:emp-mariam": 15,
  "project-jubail-shutdown:emp-fahad": 20,
  "project-jubail-shutdown:emp-ahmed": 55,
  "project-jubail-shutdown:emp-yousef": 20,
  "project-jubail-shutdown:emp-salman": 25,
  "project-jubail-shutdown:emp-lina": 35,
};

const projectAssignments = projects.flatMap((project) =>
  project.teamEmployeeIds.map((employeeId) => ({
    id: `${project.id}-${employeeId}`,
    projectId: project.id,
    employeeId,
    allocationPercent: assignmentAllocation[`${project.id}:${employeeId}`] ?? 20,
    billable: project.client !== "Rukn Energy internal",
  })),
);

const gradeByEmployee: Record<string, string> = {
  "emp-reem": "E1",
  "emp-fahad": "M1",
  "emp-aisha": "P3",
  "emp-omar": "P2",
  "emp-priya": "P2",
  "emp-noura": "P3",
  "emp-khalid": "M1",
  "emp-mariam": "M1",
  "emp-yousef": "P4",
  "emp-ahmed": "P3",
  "emp-lina": "P2",
  "emp-salman": "M2",
};

const compensation = employees.map((employee) => ({
  id: `comp-2026-${employee.id}`,
  employeeId: employee.id,
  effectiveDate: employee.hireDate > "2026-01-01" ? employee.hireDate : "2026-01-01",
  grade: gradeByEmployee[employee.id] ?? "P2",
  currency: "SAR" as const,
  basic: employee.salary.basic,
  housing: employee.salary.housing,
  transport: employee.salary.transport,
  annualBonusTargetPercent: employee.role === "department_manager" || employee.role === "hr_manager" ? 15 : 8,
  reviewReason: employee.hireDate > "2026-01-01" ? "New hire package" : "2026 annual salary review",
  approvedByEmployeeId: employee.id === "emp-reem" ? "emp-mariam" : "emp-reem",
}));

const variablePay: Record<string, { projectAllowance: number; overtime: number; bonus: number; otherDeductions: number }> = {
  "emp-reem": { projectAllowance: 0, overtime: 0, bonus: 3_000, otherDeductions: 0 },
  "emp-fahad": { projectAllowance: 2_000, overtime: 0, bonus: 0, otherDeductions: 0 },
  "emp-aisha": { projectAllowance: 0, overtime: 0, bonus: 1_500, otherDeductions: 0 },
  "emp-omar": { projectAllowance: 1_200, overtime: 850, bonus: 0, otherDeductions: 0 },
  "emp-priya": { projectAllowance: 700, overtime: 0, bonus: 0, otherDeductions: 0 },
  "emp-noura": { projectAllowance: 0, overtime: 0, bonus: 1_000, otherDeductions: 0 },
  "emp-khalid": { projectAllowance: 2_500, overtime: 0, bonus: 0, otherDeductions: 0 },
  "emp-mariam": { projectAllowance: 0, overtime: 0, bonus: 2_000, otherDeductions: 0 },
  "emp-yousef": { projectAllowance: 1_800, overtime: 1_200, bonus: 0, otherDeductions: 0 },
  "emp-ahmed": { projectAllowance: 1_200, overtime: 950, bonus: 0, otherDeductions: 800 },
  "emp-lina": { projectAllowance: 1_000, overtime: 0, bonus: 0, otherDeductions: 0 },
  "emp-salman": { projectAllowance: 900, overtime: 600, bonus: 0, otherDeductions: 0 },
};

const payslips = employees.map((employee) => {
  const variable = variablePay[employee.id] ?? { projectAllowance: 0, overtime: 0, bonus: 0, otherDeductions: 0 };
  const contributionBase = employee.salary.basic + employee.salary.housing;
  const employeeRate = employee.nationality === "expat" ? 0 : employee.gosiCohort === "new_entrant" ? 0.1075 : 0.0975;
  const employerRate = employee.nationality === "expat" ? 0.02 : employee.gosiCohort === "new_entrant" ? 0.1275 : 0.1175;
  const employeeGosi = Math.round(contributionBase * employeeRate);
  const employerGosi = Math.round(contributionBase * employerRate);
  const earnings = {
    basic: employee.salary.basic,
    housing: employee.salary.housing,
    transport: employee.salary.transport,
    projectAllowance: variable.projectAllowance,
    overtime: variable.overtime,
    bonus: variable.bonus,
  };
  const gross = Object.values(earnings).reduce((sum, amount) => sum + amount, 0);
  const deductions = employeeGosi + variable.otherDeductions;
  return {
    id: `slip-jun-2026-${employee.id}`,
    employeeId: employee.id,
    period: "June 2026",
    earnings,
    contributionBase,
    employeeGosi,
    employerGosi,
    otherDeductions: variable.otherDeductions,
    gross,
    deductions,
    net: gross - deductions,
    status: "ready" as const,
    bankStatus: "validated" as const,
    calculationMode: "illustrative_fixture_not_for_real_payroll" as const,
    documentUrl: `/demo/documents/${employee.employeeNumber.toLowerCase()}-jun-2026-payslip.pdf`,
  };
});

const currentGross = payslips.reduce((sum, payslip) => sum + payslip.gross, 0);
const currentNet = payslips.reduce((sum, payslip) => sum + payslip.net, 0);

const contractDocuments = employees.map((employee, index) => ({
  id: `doc-contract-${String(index + 1).padStart(2, "0")}`,
  employeeId: employee.id,
  type: "Employment contract",
  name: `${employee.fullName} bilingual employment contract`,
  status: "valid" as const,
  expiryDate: null,
}));

export const taazurEnergyDemo = {
  disclosure: "Fictional customer-demo data. No record represents a real person or company.",
  company: {
    id: "rukn-energy-demo",
    name: "Rukn Energy Services (Demo)",
    nameAr: "ركن الطاقة لخدمات الطاقة (تجريبي)",
    industry: "Oilfield services and energy operations",
    crNumber: "DEMO-CR-2050",
    nitaqatBand: "Illustrative Green scenario",
    saudizationRate: 83,
    headcount: employees.length,
    payrollCurrency: "SAR",
    payrollDay: 27,
  },
  branches,
  departments,
  positions: [
    ...employees.map((employee) => ({ id: `position-${employee.id}`, title: employee.jobTitle, departmentId: employee.departmentId, incumbentEmployeeId: employee.id, status: "filled" as const })),
    { id: "position-drilling-02", title: "Drilling Engineer", departmentId: "dept-field", incumbentEmployeeId: null, status: "open" as const },
    { id: "position-project-planner", title: "Project Planner", departmentId: "dept-projects", incumbentEmployeeId: null, status: "open" as const },
  ],
  employees,
  projects,
  projectAssignments,
  compensation,
  attendance: {
    date: "2026-07-13",
    present: 10,
    exceptions: 2,
    entries: [
      { employeeId: "emp-reem", checkIn: "08:07", status: "present", location: "Riyadh HQ" },
      { employeeId: "emp-fahad", checkIn: "06:42", status: "present", location: "Dhahran Base" },
      { employeeId: "emp-aisha", checkIn: "08:31", status: "late", location: "Riyadh HQ" },
      { employeeId: "emp-omar", checkIn: "06:28", status: "present", location: "Field Rotation A" },
      { employeeId: "emp-priya", checkIn: null, status: "approved_leave", location: "Dhahran Base" },
      { employeeId: "emp-noura", checkIn: "08:12", status: "present", location: "Riyadh HQ" },
      { employeeId: "emp-khalid", checkIn: "07:16", status: "present", location: "Jubail Project Office" },
      { employeeId: "emp-mariam", checkIn: "08:03", status: "present", location: "Riyadh HQ" },
      { employeeId: "emp-yousef", checkIn: "06:21", status: "present", location: "Field Rotation B" },
      { employeeId: "emp-ahmed", checkIn: "05:58", status: "present", location: "Dhahran Workshop" },
      { employeeId: "emp-lina", checkIn: "07:44", status: "present", location: "Jubail Project Office" },
      { employeeId: "emp-salman", checkIn: "06:37", status: "present", location: "Dhahran Base" },
    ],
  },
  shifts: [
    { id: "shift-corporate", name: "Corporate day", start: "08:00", end: "17:00", days: "Sun–Thu" },
    { id: "shift-field-a", name: "Field Rotation A", start: "06:00", end: "18:00", days: "14/7 rotation" },
    { id: "shift-field-b", name: "Field Rotation B", start: "18:00", end: "06:00", days: "14/7 rotation" },
    { id: "shift-maintenance", name: "Maintenance early", start: "05:30", end: "14:30", days: "Rotating" },
  ],
  shiftAssignments: employees.map((employee) => ({
    employeeId: employee.id,
    shiftId: employee.id === "emp-ahmed" ? "shift-maintenance" : employee.branchId === "riyadh-hq" || employee.branchId === "jubail-site" ? "shift-corporate" : employee.id === "emp-yousef" ? "shift-field-b" : "shift-field-a",
    effectiveDate: "2026-07-01",
  })),
  leave: {
    balances: employees.map((employee) => ({ employeeId: employee.id, annualEntitlement: employee.hireDate < "2021-07-13" ? 30 : 21, annualRemaining: employee.id === "emp-priya" ? 4 : employee.id === "emp-omar" ? 18 : 14, sickUsed: employee.id === "emp-ahmed" ? 3 : 0 })),
    requests: [
      { id: "leave-001", employeeId: "emp-priya", type: "Annual leave", from: "2026-07-13", to: "2026-07-14", status: "approved", approverId: "emp-salman" },
      { id: "leave-002", employeeId: "emp-omar", type: "Personal leave", from: "2026-07-20", to: "2026-07-20", status: "pending", approverId: "emp-fahad" },
      { id: "leave-003", employeeId: "emp-noura", type: "Annual leave", from: "2026-08-02", to: "2026-08-06", status: "approved", approverId: "emp-reem" },
      { id: "leave-004", employeeId: "emp-ahmed", type: "Sick leave", from: "2026-06-21", to: "2026-06-23", status: "approved", approverId: "emp-fahad" },
      { id: "leave-005", employeeId: "emp-lina", type: "Examination leave", from: "2026-07-27", to: "2026-07-27", status: "pending", approverId: "emp-khalid" },
      { id: "leave-006", employeeId: "emp-yousef", type: "Annual leave", from: "2026-09-06", to: "2026-09-17", status: "draft", approverId: "emp-fahad" },
    ],
  },
  payroll: {
    period: "June 2026",
    status: "ready_for_submission",
    currency: "SAR",
    gross: currentGross,
    net: currentNet,
    anomalies: [
      { id: "pay-anomaly-01", employeeId: "emp-omar", severity: "low", message: "First full payroll cycle — confirm project allowance." },
      { id: "pay-anomaly-02", employeeId: "emp-ahmed", severity: "medium", message: "Loan deduction requires employee acknowledgment." },
    ],
    runs: [
      { id: "payroll-apr-2026", period: "April 2026", employeeCount: 10, gross: Math.round(currentGross * 0.82), net: Math.round(currentNet * 0.82), status: "paid", paidAt: "2026-04-27" },
      { id: "payroll-may-2026", period: "May 2026", employeeCount: 11, gross: Math.round(currentGross * 0.91), net: Math.round(currentNet * 0.91), status: "paid", paidAt: "2026-05-27" },
      { id: "payroll-jun-2026", period: "June 2026", employeeCount: 12, gross: currentGross, net: currentNet, status: "ready_for_submission", paidAt: null },
    ],
    payslips,
  },
  documents: [
    ...contractDocuments,
    { id: "doc-hse-fahad", employeeId: "emp-fahad", type: "HSE certificate", name: "Operational safety leadership", status: "expiring_soon", expiryDate: "2026-08-22" },
    { id: "doc-gosi-aisha", employeeId: "emp-aisha", type: "GOSI registration", name: "GOSI enrollment confirmation", status: "valid", expiryDate: null },
    { id: "doc-iqama-priya", employeeId: "emp-priya", type: "Iqama", name: "Resident identity", status: "expiring_soon", expiryDate: "2026-09-10" },
    { id: "doc-passport-priya", employeeId: "emp-priya", type: "Passport", name: "Passport copy", status: "valid", expiryDate: "2028-02-18" },
    { id: "doc-iqama-ahmed", employeeId: "emp-ahmed", type: "Iqama", name: "Resident identity", status: "valid", expiryDate: "2027-03-11" },
    { id: "doc-pmp-khalid", employeeId: "emp-khalid", type: "Professional certificate", name: "Project management certification", status: "valid", expiryDate: "2028-05-30" },
    { id: "doc-nebosh-salman", employeeId: "emp-salman", type: "HSE certificate", name: "NEBOSH International General Certificate", status: "valid", expiryDate: null },
    { id: "doc-offboarding-priya", employeeId: "emp-priya", type: "Exit checklist", name: "Controlled offboarding pack", status: "in_progress", expiryDate: null },
  ],
  recruitment: {
    requisitions: [
      { id: "req-01", title: "Drilling Engineer", departmentId: "dept-field", branchId: "dhahran-ops", hiringManagerId: "emp-fahad", recruiterId: "emp-noura", openings: 1, status: "interviewing" },
      { id: "req-02", title: "Project Planner", departmentId: "dept-projects", branchId: "jubail-site", hiringManagerId: "emp-khalid", recruiterId: "emp-noura", openings: 1, status: "offer" },
      { id: "req-03", title: "Payroll Officer", departmentId: "dept-people", branchId: "riyadh-hq", hiringManagerId: "emp-reem", recruiterId: "emp-noura", openings: 1, status: "sourcing" },
    ],
    candidates: [
      { id: "candidate-sara", name: "Sara Al-Mutairi", email: "sara.almutairi@candidate.example", stage: "technical_interview", score: 88 },
      { id: "candidate-abdullah", name: "Abdullah Al-Salem", email: "abdullah.alsalem@candidate.example", stage: "offer", score: 91 },
      { id: "candidate-fatima", name: "Fatima Al-Dosari", email: "fatima.aldosari@candidate.example", stage: "screening", score: 82 },
      { id: "candidate-jose", name: "Jose Dela Cruz", email: "jose.delacruz@candidate.example", stage: "rejected", score: 71 },
    ],
    applications: [
      { id: "app-01", candidateId: "candidate-sara", requisitionId: "req-01", stage: "technical_interview", nextAction: "Panel interview · 15 Jul" },
      { id: "app-02", candidateId: "candidate-abdullah", requisitionId: "req-02", stage: "offer", nextAction: "Approve bilingual offer" },
      { id: "app-03", candidateId: "candidate-fatima", requisitionId: "req-03", stage: "screening", nextAction: "Payroll assessment" },
      { id: "app-04", candidateId: "candidate-jose", requisitionId: "req-01", stage: "rejected", nextAction: "Archive after notice" },
    ],
    interviews: [
      { id: "int-01", applicationId: "app-01", panel: ["emp-fahad", "emp-yousef", "emp-noura"], scheduledAt: "2026-07-15T10:00:00+03:00", location: "Teams" },
      { id: "int-02", applicationId: "app-02", panel: ["emp-khalid", "emp-lina", "emp-noura"], scheduledAt: "2026-07-12T13:30:00+03:00", location: "Jubail Office" },
      { id: "int-03", applicationId: "app-03", panel: ["emp-aisha", "emp-noura"], scheduledAt: "2026-07-18T11:00:00+03:00", location: "Riyadh HQ" },
    ],
    offers: [
      { id: "offer-01", candidateId: "candidate-sara", requisitionId: "req-01", status: "draft", basicSalary: 21_000, startDate: "2026-08-16" },
      { id: "offer-02", candidateId: "candidate-abdullah", requisitionId: "req-02", status: "approval_pending", basicSalary: 18_500, startDate: "2026-09-01" },
    ],
  },
  onboarding: {
    employeeId: "emp-omar",
    progress: 78,
    buddyId: "emp-yousef",
    tasks: [
      { id: "onb-01", subjectId: "emp-omar", label: "Contract and GOSI registration", owner: "People & Culture", status: "done" },
      { id: "onb-02", subjectId: "emp-omar", label: "Field safety induction", owner: "HSE", status: "done" },
      { id: "onb-03", subjectId: "emp-omar", label: "Laptop, badge, and PPE handover", owner: "Operations IT", status: "done" },
      { id: "onb-04", subjectId: "emp-omar", label: "30-day manager check-in", owner: "emp-fahad", status: "due" },
    ],
    cohorts: [
      { id: "cohort-omar", subjectId: "emp-omar", subjectType: "employee", role: "Field Engineer", managerId: "emp-fahad", buddyId: "emp-yousef", startDate: "2026-05-03", progress: 78, status: "in_progress" },
      { id: "cohort-sara", subjectId: "candidate-sara", subjectType: "candidate", role: "Drilling Engineer", managerId: "emp-fahad", buddyId: "emp-omar", startDate: "2026-08-16", progress: 35, status: "preboarding" },
      { id: "cohort-lina", subjectId: "emp-lina", subjectType: "employee", role: "Project Coordinator", managerId: "emp-khalid", buddyId: "emp-noura", startDate: "2025-11-02", progress: 100, status: "complete" },
    ],
  },
  performance: {
    goals: [
      { id: "goal-01", employeeId: "emp-omar", managerId: "emp-fahad", title: "Complete field certification", progress: 65, dueDate: "2026-08-31" },
      { id: "goal-02", employeeId: "emp-aisha", managerId: "emp-reem", title: "Zero-error Mudad submissions", progress: 92, dueDate: "2026-12-31" },
      { id: "goal-03", employeeId: "emp-khalid", managerId: "emp-reem", title: "Deliver Jafurah mobilization gate", progress: 68, dueDate: "2026-09-30" },
      { id: "goal-04", employeeId: "emp-noura", managerId: "emp-reem", title: "Reduce time-to-offer to 18 days", progress: 74, dueDate: "2026-10-31" },
      { id: "goal-05", employeeId: "emp-salman", managerId: "emp-fahad", title: "Close all high-risk HSE actions", progress: 86, dueDate: "2026-08-15" },
      { id: "goal-06", employeeId: "emp-lina", managerId: "emp-khalid", title: "Automate weekly project reporting", progress: 55, dueDate: "2026-09-15" },
    ],
    reviewCycle: { id: "review-h1-2026", name: "H1 2026 Growth Review", completion: 83, status: "manager_review", participants: 12 },
    learning: [
      { id: "learn-01", employeeId: "emp-omar", title: "Advanced well-control fundamentals", status: "in_progress", progress: 40 },
      { id: "learn-02", employeeId: "emp-lina", title: "Primavera P6 foundations", status: "in_progress", progress: 62 },
      { id: "learn-03", employeeId: "emp-noura", title: "Structured technical interviewing", status: "complete", progress: 100 },
      { id: "learn-04", employeeId: "emp-ahmed", title: "Reliability-centered maintenance", status: "in_progress", progress: 35 },
      { id: "learn-05", employeeId: "emp-salman", title: "Incident investigation lead", status: "assigned", progress: 0 },
    ],
    recognitions: [
      { id: "rec-01", employeeId: "emp-aisha", fromEmployeeId: "emp-reem", value: "Precision", message: "Closed payroll pre-checks with zero critical findings." },
      { id: "rec-02", employeeId: "emp-yousef", fromEmployeeId: "emp-fahad", value: "Safety", message: "Stopped a field task and corrected the permit before work resumed." },
      { id: "rec-03", employeeId: "emp-lina", fromEmployeeId: "emp-khalid", value: "Collaboration", message: "Connected three project teams through one weekly control pack." },
    ],
  },
  benefits: {
    plans: [
      { id: "benefit-medical-executive", name: "Executive medical", provider: "Fictional Gulf Health", class: "VIP", dependantsCovered: true },
      { id: "benefit-medical-family", name: "Family medical", provider: "Fictional Gulf Health", class: "A", dependantsCovered: true },
      { id: "benefit-medical-standard", name: "Standard medical", provider: "Fictional Gulf Health", class: "B", dependantsCovered: false },
      { id: "benefit-life", name: "Group life", provider: "Fictional Takaful", class: "2× annual basic", dependantsCovered: false },
    ],
    enrollments: employees.map((employee) => ({ employeeId: employee.id, planId: employee.healthPlanId, status: "active", effectiveDate: employee.hireDate, dependantCount: employee.healthPlanId === "benefit-medical-family" ? 2 : employee.healthPlanId === "benefit-medical-executive" ? 3 : 0 })),
  },
  assets: employees.map((employee, index) => ({
    id: `asset-${String(index + 1).padStart(2, "0")}`,
    employeeId: employee.id,
    type: employee.departmentId === "dept-field" || employee.departmentId === "dept-hse" ? "Rugged tablet + PPE kit" : "Laptop + access badge",
    assetTag: `RUKN-${2026001 + index}`,
    status: employee.status === "notice_period" ? "return_due" : "assigned",
    assignedAt: employee.hireDate,
  })),
  engagement: {
    eNps: 42,
    responseRate: 83,
    invited: 12,
    responses: 10,
    pulse: [
      { topic: "Manager support", score: 4.4 },
      { topic: "Workload", score: 3.7 },
      { topic: "Safety culture", score: 4.7 },
      { topic: "Career growth", score: 3.9 },
      { topic: "Tools and systems", score: 4.1 },
    ],
  },
  expenses: [
    { id: "exp-01", employeeId: "emp-fahad", projectId: "project-jafurah", category: "Dhahran–Riyadh travel", amount: 1_840, currency: "SAR", status: "approved" },
    { id: "exp-02", employeeId: "emp-omar", projectId: "project-jafurah", category: "Field per diem", amount: 620, currency: "SAR", status: "pending" },
    { id: "exp-03", employeeId: "emp-khalid", projectId: "project-jubail-shutdown", category: "Client workshop", amount: 2_450, currency: "SAR", status: "approved" },
    { id: "exp-04", employeeId: "emp-lina", projectId: "project-jubail-shutdown", category: "Project supplies", amount: 380, currency: "SAR", status: "approved" },
    { id: "exp-05", employeeId: "emp-salman", projectId: "project-hse-digital", category: "HSE inspection travel", amount: 910, currency: "SAR", status: "pending" },
    { id: "exp-06", employeeId: "emp-noura", projectId: "project-hr-transform", category: "Recruitment event", amount: 1_200, currency: "SAR", status: "draft" },
  ],
  employeeRelations: {
    openCases: 2,
    cases: [
      { id: "case-01", category: "Work schedule clarification", confidentiality: "restricted", status: "mediation", ownerId: "emp-reem", subjectEmployeeId: "emp-ahmed" },
      { id: "case-02", category: "Flexible work request", confidentiality: "restricted", status: "review", ownerId: "emp-aisha", subjectEmployeeId: "emp-noura" },
    ],
  },
  offboarding: {
    employeeId: "emp-priya",
    lastWorkingDay: "2026-08-13",
    checklist: [
      { task: "Knowledge-transfer dashboard", ownerId: "emp-priya", status: "in_progress" },
      { task: "Return access badge and laptop", ownerId: "emp-ahmed", status: "not_started" },
      { task: "Final settlement review", ownerId: "emp-aisha", status: "not_started" },
      { task: "Cancel medical insurance", ownerId: "emp-noura", status: "not_started" },
      { task: "Archive Muqeem final-exit evidence", ownerId: "emp-aisha", status: "not_started" },
    ],
    exitInterview: { scheduledAt: "2026-08-10T14:00:00+03:00", interviewerId: "emp-reem", themes: ["Career growth", "Relocation"], status: "scheduled" },
    rehireEligibility: "eligible",
  },
  reports: [
    { id: "report-workforce", name: "Workforce snapshot", cadence: "Weekly", ownerId: "emp-reem", recipients: ["HR leadership", "Finance"], status: "scheduled" },
    { id: "report-payroll", name: "Payroll variance", cadence: "Monthly", ownerId: "emp-aisha", recipients: ["Payroll", "Finance"], status: "ready" },
    { id: "report-project", name: "Project utilization", cadence: "Weekly", ownerId: "emp-khalid", recipients: ["PMO", "Operations"], status: "scheduled" },
    { id: "report-hse", name: "HSE leading indicators", cadence: "Monthly", ownerId: "emp-salman", recipients: ["Leadership", "Operations"], status: "ready" },
  ],
  workflows: [
    { id: "workflow-expiry", name: "Document expiry reminder", trigger: "60/30/7 days before expiry", status: "active", runsThisMonth: 8 },
    { id: "workflow-onboarding", name: "New-hire onboarding", trigger: "Offer accepted", status: "active", runsThisMonth: 3 },
    { id: "workflow-expense", name: "Expense approval", trigger: "Claim submitted", status: "active", runsThisMonth: 12 },
    { id: "workflow-probation", name: "Probation milestones", trigger: "30/90/150 days", status: "draft", runsThisMonth: 4 },
  ],
  governmentIntegrations: [
    { id: "qiwa", name: "Qiwa", mode: "mock", status: "sandbox_ready", lastReference: "QIW-MOCK-260713-01" },
    { id: "mudad", name: "Mudad / WPS", mode: "mock", status: "file_validated", lastReference: "MUD-MOCK-260713-01" },
    { id: "gosi", name: "GOSI", mode: "mock", status: "reconciliation_ready", lastReference: "GOS-MOCK-260713-01" },
    { id: "muqeem", name: "Muqeem", mode: "mock", status: "expiry_checked", lastReference: "MUQ-MOCK-260713-01" },
    { id: "bank", name: "Bank payroll", mode: "mock", status: "payment_file_ready", lastReference: "BNK-MOCK-260713-01" },
    { id: "zatca", name: "ZATCA", mode: "mock", status: "scope_confirmation_required", lastReference: "ZAT-MOCK-260713-01" },
  ],
} as const;

export type TaazurEnergyDemo = typeof taazurEnergyDemo;

export function getDemoEmployee(employeeId: string | null | undefined) {
  if (!employeeId) return undefined;
  return taazurEnergyDemo.employees.find((employee) => employee.id === employeeId);
}
