export type ModuleStatus = "live" | "demo" | "mock";

export interface ProductModule {
  slug: string;
  name: string;
  nameAr: string;
  eyebrow: string;
  description: string;
  phase: 1 | 2 | 3 | 4 | 5;
  status: ModuleStatus;
  href?: string;
  featureIds: string[];
  capabilities: string[];
}

export const productModules: ProductModule[] = [
  {
    slug: "people-organization",
    name: "People & Organization",
    nameAr: "الأفراد والهيكل التنظيمي",
    eyebrow: "Core HR",
    description: "Employee master records, departments, reporting lines, dual dates, RBAC and self-service.",
    phase: 1,
    status: "live",
    href: "/employees",
    featureIds: ["1.1", "1.2", "1.10", "1.11", "1.13"],
    capabilities: ["Employee 360 profiles", "Organization structure", "Role-aware access", "Hijri + Gregorian dates"],
  },
  {
    slug: "company-onboarding",
    name: "Company Onboarding",
    nameAr: "تهيئة الشركة",
    eyebrow: "Administration",
    description: "CR details, Nitaqat activity, bank configuration, allowances and multi-company setup.",
    phase: 1,
    status: "demo",
    href: "/settings",
    featureIds: ["1.12", "5.7"],
    capabilities: ["Company setup wizard", "Schema-per-tenant isolation", "Subsidiary management", "Consolidated reporting"],
  },
  {
    slug: "payroll-settlement",
    name: "Payroll & Final Settlement",
    nameAr: "الرواتب والتسوية النهائية",
    eyebrow: "Saudi Payroll",
    description: "Saudi payroll, GOSI calculations, end-of-service benefits, bilingual payslips and anomaly controls.",
    phase: 1,
    status: "live",
    href: "/payroll",
    featureIds: ["1.3", "1.4", "1.6", "1.8", "3.11"],
    capabilities: ["Monthly payroll runs", "GOSI dual-rate logic", "ESB settlement", "Bilingual payslips"],
  },
  {
    slug: "time-leave-attendance",
    name: "Time, Leave & Attendance",
    nameAr: "الوقت والإجازات والحضور",
    eyebrow: "Workforce Operations",
    description: "Saudi leave policies, balances, approvals, attendance, shifts and Ramadan schedules.",
    phase: 1,
    status: "live",
    href: "/leave",
    featureIds: ["1.9", "4.8"],
    capabilities: ["Saudi leave types", "Approval workflows", "Shift templates", "Ramadan hour rules"],
  },
  {
    slug: "documents-certificates",
    name: "Documents & Certificates",
    nameAr: "المستندات والشهادات",
    eyebrow: "Employee Records",
    description: "Secure document storage, versioning, expiry alerts, licenses and professional certificates.",
    phase: 1,
    status: "live",
    href: "/documents",
    featureIds: ["1.7", "2.13"],
    capabilities: ["Document vault", "90/60/30 expiry alerts", "Certificate tracking", "Employee uploads"],
  },
  {
    slug: "notifications-reports",
    name: "Notifications & Reports",
    nameAr: "الإشعارات والتقارير",
    eyebrow: "Operations Intelligence",
    description: "Approval reminders, payroll alerts and foundational workforce reports.",
    phase: 1,
    status: "demo",
    featureIds: ["1.14", "1.15", "4.10"],
    capabilities: ["Email, SMS and in-app alerts", "Headcount reports", "Payroll summaries", "Configurable KPI boards"],
  },
  {
    slug: "recruitment",
    name: "Recruitment & Candidate CRM",
    nameAr: "التوظيف وإدارة المرشحين",
    eyebrow: "Talent Acquisition",
    description: "Jobs, candidates, applications, AI screening, interviews, offers and branded careers.",
    phase: 2,
    status: "live",
    href: "/recruitment",
    featureIds: ["2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "5.4"],
    capabilities: ["Recruitment pipeline", "Candidate database", "Interview scheduling", "Bilingual offer letters"],
  },
  {
    slug: "onboarding",
    name: "Onboarding & New-Hire Copilot",
    nameAr: "التهيئة ومساعد الموظف الجديد",
    eyebrow: "Employee Lifecycle",
    description: "Role-based onboarding, 30/60/90 plans, buddy assignment and employee Q&A.",
    phase: 2,
    status: "demo",
    href: "/recruitment/onboarding",
    featureIds: ["2.8", "2.9"],
    capabilities: ["30/60/90 plans", "Role-specific checklists", "Buddy assignment", "AI onboarding copilot"],
  },
  {
    slug: "offboarding",
    name: "Offboarding & Alumni",
    nameAr: "إنهاء الخدمة والخريجون",
    eyebrow: "Employee Lifecycle",
    description: "Exit orchestration, knowledge transfer, access revocation, final settlement and rehire tracking.",
    phase: 2,
    status: "demo",
    featureIds: ["2.10"],
    capabilities: ["Exit checklist", "Asset and access closure", "Knowledge-transfer handover", "Rehire eligibility"],
  },
  {
    slug: "learning-skills",
    name: "Learning, Skills & Career",
    nameAr: "التعلم والمهارات والمسار المهني",
    eyebrow: "Talent Development",
    description: "Competencies, skill gaps, learning catalog, certificates and career pathways.",
    phase: 2,
    status: "demo",
    href: "/retention/skills",
    featureIds: ["2.11", "2.12", "2.13"],
    capabilities: ["Competency profiles", "Skill-gap analysis", "Training catalog", "Career pathways"],
  },
  {
    slug: "benefits-rewards",
    name: "Benefits, Rewards & Recognition",
    nameAr: "المزايا والمكافآت والتقدير",
    eyebrow: "Total Rewards",
    description: "Benefits packages, compensation bands, pay equity, recognition and payroll-linked spot bonuses.",
    phase: 2,
    status: "demo",
    href: "/retention/rewards",
    featureIds: ["2.14", "4.11", "4.12"],
    capabilities: ["Benefits packages", "Pay bands", "Pay-equity view", "Recognition feed"],
  },
  {
    slug: "government-integrations",
    name: "Government integrations",
    nameAr: "التكاملات الحكومية",
    eyebrow: "Saudi compliance",
    description: "Multi-authority sync, workflows and evidence exchange across the Saudi ecosystem.",
    phase: 3,
    status: "mock",
    href: "/qiwa",
    featureIds: ["1.5", "3.1", "3.2", "3.3", "3.4", "3.5", "5.6"],
    capabilities: ["Qiwa contracts", "Mudad wage submission", "GOSI reporting", "Muqeem and banking"],
  },
  {
    slug: "nitaqat-compliance",
    name: "Nitaqat & Compliance",
    nameAr: "نطاقات والامتثال",
    eyebrow: "Saudi Compliance",
    description: "Compliance checks, Saudization tracking, scenario simulation and regulatory configuration.",
    phase: 3,
    status: "live",
    href: "/compliance",
    featureIds: ["3.6", "3.12", "3.13", "5.3"],
    capabilities: ["Nitaqat band tracking", "What-if simulator", "Regulatory config", "Pre-submission controls"],
  },
  {
    slug: "ai-intelligence",
    name: "AI Workforce Intelligence",
    nameAr: "ذكاء القوى العاملة",
    eyebrow: "AI Native",
    description: "Executive briefs, cost forecasts, attrition signals, compliance answers and anomaly narratives.",
    phase: 3,
    status: "demo",
    href: "/ai",
    featureIds: ["3.7", "3.8", "3.9", "3.10", "3.11", "4.3", "5.2", "5.5"],
    capabilities: ["Executive briefings", "Cost prediction", "Attrition analysis", "Saudi compliance copilot"],
  },
  {
    slug: "performance-goals",
    name: "Performance, Goals & Probation",
    nameAr: "الأداء والأهداف وفترة التجربة",
    eyebrow: "Talent Management",
    description: "Review cycles, goals, AI-assisted summaries and Saudi probation milestones.",
    phase: 4,
    status: "demo",
    href: "/retention/reviews",
    featureIds: ["4.1", "4.2", "4.3", "4.4"],
    capabilities: ["Review cycles", "Goals and OKRs", "AI review drafts", "180-day probation tracking"],
  },
  {
    slug: "engagement-retention",
    name: "Engagement & Retention",
    nameAr: "المشاركة والاحتفاظ",
    eyebrow: "Employee Experience",
    description: "Pulse surveys, eNPS, employer brand, stay interviews and retention insights.",
    phase: 4,
    status: "demo",
    href: "/retention/engagement",
    featureIds: ["4.5", "4.9", "4.13"],
    capabilities: ["Pulse surveys", "eNPS trends", "Employer branding", "Stay interviews"],
  },
  {
    slug: "travel-expenses",
    name: "Travel, Expenses & Delegation",
    nameAr: "السفر والمصروفات والانتداب",
    eyebrow: "Workforce Operations",
    description: "Trips, receipts, multi-currency expenses, per-diem and approval delegation.",
    phase: 4,
    status: "demo",
    featureIds: ["4.6", "4.7"],
    capabilities: ["Trip planning", "Expense claims", "Per-diem calculation", "Delegated approvals"],
  },
  {
    slug: "employee-relations",
    name: "Employee Relations & Cases",
    nameAr: "علاقات الموظفين وإدارة القضايا",
    eyebrow: "HR Generalist",
    description: "Confidential grievances, disciplinary actions, investigations and resolution records.",
    phase: 4,
    status: "demo",
    featureIds: ["4.14"],
    capabilities: ["Grievance intake", "Disciplinary actions", "Investigation files", "Resolution audit trail"],
  },
  {
    slug: "mobile-self-service",
    name: "Mobile & Self-Service",
    nameAr: "الجوال والخدمة الذاتية",
    eyebrow: "Employee Experience",
    description: "Arabic-first mobile access for leave, payslips, approvals, attendance and copilot.",
    phase: 5,
    status: "demo",
    featureIds: ["5.1"],
    capabilities: ["iOS and Android", "Arabic-first UX", "Mobile approvals", "Document capture"],
  },
  {
    slug: "workflow-automation",
    name: "Autonomous Workflows",
    nameAr: "سير العمل الذاتي",
    eyebrow: "Automation",
    description: "AI agents and no-code workflows for approvals, escalations and repetitive HR operations.",
    phase: 5,
    status: "demo",
    featureIds: ["5.2", "5.8"],
    capabilities: ["Multi-step HR agents", "No-code workflow builder", "Escalation rules", "Human approval gates"],
  },
  {
    slug: "people-analytics",
    name: "People Analytics",
    nameAr: "تحليلات الأفراد",
    eyebrow: "Executive Intelligence",
    description: "Cross-module analytics for recruitment, retention, compensation and workforce diversity.",
    phase: 5,
    status: "demo",
    featureIds: ["5.5"],
    capabilities: ["Recruitment funnel", "Retention cohorts", "Compensation benchmarks", "Diversity metrics"],
  },
  {
    slug: "integration-marketplace",
    name: "API & Integration Marketplace",
    nameAr: "واجهة البرمجة وسوق التكاملات",
    eyebrow: "Platform",
    description: "Open APIs and connectors for accounting, ERP, payroll and government services.",
    phase: 5,
    status: "demo",
    featureIds: ["5.9"],
    capabilities: ["Public API", "Qoyod and Wafeq", "SAP and Odoo", "Integration monitoring"],
  },
];

export const moduleStatusLabels: Record<ModuleStatus, string> = {
  live: "Live workspace",
  demo: "Operational demo",
  mock: "Mock integration",
};

export function getProductModule(slug: string) {
  return productModules.find((module) => module.slug === slug);
}

export const totalPrdFeatures = new Set(productModules.flatMap((module) => module.featureIds)).size;
